apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82022007-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: "82022007-prod.cepg-aa.kubepia.net"
    http:
      paths:
      - path: /
        backend:
          service:
            name: "82022007"
            port:
              number: 8080
        pathType: Prefix
