configMapGenerator:
- files:
  - application.yml
  name: 82022007-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82022007
  newTag: "202411110558"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202411110223"
